### ISSUE TITLE
PBFT implementation

### ISSUE THREAD

**Issue by donovanhide** [hyperledger/hyperledger-server#4]
Hi,

just following the project! Could you point me towards the code dealing with the PBFT consensus in the current implementation? Much appreciated!

**Comment by DanielFeichtinger** [comment]
Hi there,

It's currently a little scattered through the project rather than being in one place; once things settle down a little I plan to pull it out into a clear module. However, the key models and controllers to look at are the LogEntry and Node ones — they handle storing operations and broadcasting them to the rest of the pool.
